name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        id: terraform_apply
        run: |
          terraform apply -auto-approve
          echo "deployment_host_ip=$(terraform output -raw deployment_host_ip)" >> "$GITHUB_OUTPUT"
        working-directory: ./terraform

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull docker.io/shykoh/devpipe:${{ github.event.workflow_run.head_sha }}

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ steps.terraform_apply.outputs.deployment_host_ip }}
          SSH_USER: ${{ secrets.SSH_USER }}
          DOCKER_IMAGE: docker.io/shykoh/devpipe:${{ github.event.workflow_run.head_sha }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" "
            docker stop devpipe-app || true
            docker rm devpipe-app || true
            docker pull ${{ env.DOCKER_IMAGE }}
            docker run -d --name devpipe-app -p 80:3000 ${{ env.DOCKER_IMAGE }}
          "
          